env:
  global:
    - Features=use-mock-crust
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
branches:
  only:
    - master
    - stable
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
cache:
  cargo: true
before_script:
  - (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update
  - (which rustfmt && cargo install-update rustfmt) || cargo install rustfmt
  - (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
script:
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_rustfmt.sh | bash &&
        cargo rustc --verbose -- --test -Zno-trans &&
        cargo rustc --verbose --example ci_test -- -Zno-trans &&
        cargo rustc --verbose --example key_value_store -- -Zno-trans &&
        cargo rustc --verbose -- -Zno-trans &&
        cargo test  --verbose --features use-mock-crust
      );
    fi
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_clippy.sh | bash
before_cache:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_cargo_prune.sh | bash
