env:
  global:
    - Features=use-mock-crust
    - RUST_BACKTRACE=1
branches:
  only:
    - master
    - stable
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
cache:
  cargo: true
script:
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_rustfmt.sh | bash &&
        cargo rustc --verbose --release -- --test -Zno-trans &&
        cargo rustc --verbose --release -- --example ci_test -Zno-trans &&
        cargo rustc --verbose --release -- --example key_value_store -Zno-trans &&
        cargo rustc --verbose --release -- -Zno-trans &&
        cargo test  --verbose --release --features use-mock-routing
      );
    fi
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_clippy.sh | bash
before_cache:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_cargo_prune.sh | bash
