env:
  global:
    - secure: 6GJFbN62dQxgdMDUCy92Wc3xHaepp3D5/AwOfKM2tfik454AeZgoymGfXD/Om9WZXcwe1ji3szzCRNqwNKTeMgxBvjof4CdoybspEzjgHo5+XpkS7nHtlD3af9HL7NDKrep194B90YIkpoy/tML9wrlVSBMhrOX8dzNNnSSijmA=
    - Features=use-mock-crust
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
branches:
  only:
    - mutable-data
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly-2016-11-17
sudo: false
cache:
  cargo: true
before_script:
  - (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update
  - (which rustfmt && cargo install-update rustfmt) || cargo install rustfmt
  - (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
script:
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        cargo fmt -- --write-mode=diff &&
        cargo rustc --verbose -- --test -Zno-trans &&
        cargo rustc --verbose --example ci_test -- -Zno-trans &&
        cargo rustc --verbose --example key_value_store -- -Zno-trans &&
        cargo rustc --verbose -- -Zno-trans &&
        cargo test  --verbose --features use-mock-crust
      );
    fi
  - curl -sSL https://github.com/maidsafe/QA/raw/master/bash_scripts/travis/run_clippy.sh | bash
before_cache:
  - cargo prune
