[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
description = "A secured storage DHT"
documentation = "http://docs.maidsafe.net/routing/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0/MaidSafe.net Commercial License 1.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.21.0"

[dependencies]
accumulator = "~0.4.0"
clippy = {version = "~0.0.71", optional = true}
crust = "~0.14.0"
itertools = "~0.4.15"
kademlia_routing_table = "~0.6.0"
log = "~0.3.6"
lru_time_cache = "~0.4.0"
maidsafe_utilities = "~0.6.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"
term = "~0.4.4"

[dev-dependencies]
docopt = "~0.6.80"
libc = "~0.2.11"

[build-dependencies]
hyper = {version = "~0.9.6", optional = true}

[features]
generate-diagrams = ["hyper"]
use-mock-crust = []

[[example]]
bench = false
name = "key_value_store"
test = false

[[example]]
bench = false
name = "ci_test"
test = false
