[package]

name = "routing"
version = "0.2.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "http://maidsafe.github.io/routing/latest/"
repository = "https://github.com/maidsafe/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"


[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "0.0.4"
rand = "*"
message_filter = "*"
lru_time_cache = "0.1.5"
accumulator = "0.0.1"
crust = "0.0.*"
docopt = "*"

[[example]]
name = "simple_key_value_store"
path = "examples/simple_key_value_store.rs"
test = true
bench = false
