[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.37.0"
edition = "2018"

[dependencies]
bincode = "1.1.4"
bls = { package = "threshold_crypto", version = "~0.3.2" }
bytes = "~0.4.12"
config_file_handler = "~0.11.0"
crossbeam-channel = "~0.3.9"
ctrlc = { version = "~3", optional = true, features = ["termination"] }
derive_more = "0.99.2"
ed25519_dalek = { package = "tmp-ed25519", version = "1.0.0-pre.3", features = ["serde"] }
env_logger = { version = "~0.7.1", optional = true }
err-derive = "~0.2.2"
fake_clock = "~0.3.0"
fxhash = "~0.2.1"
hex = "~0.2.0"
hex_fmt = "~0.1.0"
itertools = "~0.6.1"
lazy_static = { version = "~1", optional = true }
log = "~0.4.8"
lru_time_cache = "~0.8.1"
mock-quic-p2p = { git = "https://github.com/maidsafe/quic-p2p", tag = "0.4.0", optional = true }
num-bigint = "~0.1.40"
parsec = "0.6.0"
quic-p2p = "~0.4.0"
# rand in the versions used for compatibility
rand = "0.7.2"
rand_crypto = { package = "rand", version = "~0.6.5" }
rand_core = "0.5.1"
rand_os = "0.1.0"
rand_xorshift = "0.2.0"
resource_proof = "~0.8.0"
serde = { version = "~1.0.25", features = ["rc"] }
serde_derive = "~1.0.25"
serde_json = "~1.0.8"
tiny-keccak = "~1.5.0"
unwrap = "~1.2.1"

[dev-dependencies]
docopt = "~0.8.1"
env_logger = "~0.7.1"
libc = "~0.2.29"
structopt = "~0.3.9"

[features]
mock_base = [
    "lru_time_cache/fake_clock",
    "mock-quic-p2p",
    "parsec/mock",
    "parsec/malice-detection",
    "ctrlc",
    "lazy_static",
    "bls/use-insecure-test-only-mock-crypto",
    "env_logger",
]
mock = ["mock_base"]
