[package]
name = "routing"
version = "0.4.2"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "http://maidsafe.net/routing/latest"
repository = "https://github.com/maidsafe/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
maidsafe_utilities = "~0.1.3"
rustc-serialize = "~0.3.16"
cbor = "~0.3.16"
time = "~0.1.34"
rand = "~0.3.12"
message_filter = "~0.1.5"
lru_time_cache = "~0.2.4"
accumulator = "~0.1.3"
docopt = "~0.6.75"
itertools = "~0.4.3"
log = "~0.3.3"
env_logger = "~0.3.2"
sodiumoxide = "~0.0.9"
crust = "~0.6.1"

[dev-dependencies]
bit-vec = "~0.4.2"

[[example]]
name = "simple_key_value_store"
path = "examples/simple_key_value_store.rs"
test = true
bench = false

[[example]]
name = "key_value_store"
path = "examples/key_value_store.rs"
test = true
bench = false

[[bin]]
name = "node"
path = "tests/node.rs"
test = false
bench = false

[[bin]]
name = "churn_node"
path = "tests/churn_node.rs"
test = false
bench = false
