[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.37.0"

[[example]]
bench = false
name = "key_value_store"

[[example]]
bench = false
name = "ci_test"

[dependencies]
config_file_handler = "~0.11.0"
fake_clock = "~0.2.0"
hex = "~0.3.1"
itertools = "~0.7.8"
log = "~0.4.1"
lru_time_cache = "~0.8.0"
maidsafe_utilities = "~0.16.0"
num-bigint = "~0.1.43"
quick-error = "~1.2.1"
rand = "~0.4.2"
resource_proof = "~0.6.0"
safe_crypto = "~0.4.0"
serde = "~1.0.37"
serde_derive = "~1.0.37"
term = "~0.4.6"
tiny-keccak = "~1.4.2"
unwrap = "~1.2.0"

[dependencies.crust]
git = "https://github.com/maidsafe/crust"
rev = "master"

[dev-dependencies]
docopt = "~0.8.3"
libc = "~0.2.40"
serde_json = "~1.0.13"

[features]
use-mock-crust = ["lru_time_cache/fake_clock"]
use-mock-crypto = ["safe_crypto/mock"]
